import type { Metadata } from 'next'
import './globals.css'
import { ApolloWrapper } from "./ApolloWrapper";
import CustomNextUIProvider from "@/providers/CustomNextUIProvider";

// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })
// className={inter.className}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='dark'>
      <body>
        <CustomNextUIProvider>
          <ApolloWrapper>{children}</ApolloWrapper>
        </CustomNextUIProvider>
      </body>
    </html>
  )
}
